roles_combinaton = [
    [
        ["hunter", "werewolf", "seer"],
        ["thief", "werewolf", "witch"],
        ["villager", "werewolf", "witch"],
    ],
    [
        ["hunter", "werewolf", "seer", "thief"],
        ["thief", "werewolf", "witch", "villager"],
        ["villager", "werewolf", "witch", "seer"],
    ],
    [
        ["hunter", "werewolf", "seer", "thief", "witch"],
        ["thief", "werewolf", "witch", "villager", "seer"],
        ["villager", "werewolf", "witch", "seer", "hunter"],
    ],
    [
        ["hunter", "werewolf", "seer", "thief", "witch", "villager"],
        ["thief", "werewolf", "witch", "villager", "seer", "hunter"],
        ["villager", "werewolf", "witch", "seer", "hunter", "thief"],
    ],
    [
        ["hunter", "werewolf", "seer", "thief", "witch", "villager", "villager"],
        ["thief", "werewolf", "witch", "villager", "seer", "hunter", "villager"],
        ["villager", "werewolf", "witch", "seer", "hunter", "thief", "werewolf"],
    ],
    [
        [
            "hunter",
            "werewolf",
            "seer",
            "thief",
            "witch",
            "villager",
            "villager",
            "werewolf",
        ],
        [
            "thief",
            "werewolf",
            "witch",
            "villager",
            "seer",
            "hunter",
            "villager",
            "seer",
        ],
        [
            "villager",
            "werewolf",
            "witch",
            "seer",
            "hunter",
            "thief",
            "werewolf",
            "witch",
        ],
    ],
    [
        [
            "hunter",
            "werewolf",
            "seer",
            "thief",
            "witch",
            "villager",
            "villager",
            "werewolf",
            "witch",
        ],
        [
            "thief",
            "werewolf",
            "witch",
            "villager",
            "seer",
            "hunter",
            "villager",
            "seer",
            "villager",
        ],
        [
            "villager",
            "werewolf",
            "witch",
            "seer",
            "hunter",
            "thief",
            "werewolf",
            "witch",
            "hunter",
        ],
    ],
    [
        [
            "hunter",
            "werewolf",
            "seer",
            "thief",
            "witch",
            "villager",
            "villager",
            "werewolf",
            "witch",
            "seer",
        ],
        [
            "thief",
            "werewolf",
            "witch",
            "villager",
            "seer",
            "hunter",
            "villager",
            "seer",
            "villager",
            "hunter",
        ],
        [
            "villager",
            "werewolf",
            "witch",
            "seer",
            "hunter",
            "thief",
            "werewolf",
            "witch",
            "hunter",
            "thief",
        ],
    ],
]
